// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_ap1_FelixMunoz.DAL;

#nullable disable

namespace P1_ap1_FelixMunoz.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251010155548_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_ap1_FelixMunoz.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("P1_ap1_FelixMunoz.Models.EntradasHuacalesDetalle", b =>
                {
                    b.Property<int>("detalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("detalleId");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("IdTipo");

                    b.ToTable("EntradasHuacalesDetalle");
                });

            modelBuilder.Entity("P1_ap1_FelixMunoz.Models.TiposHuacales", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTipo");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            IdTipo = 1,
                            Descripcion = "Huacal Rojo - Grande",
                            Existencia = 100
                        },
                        new
                        {
                            IdTipo = 2,
                            Descripcion = "Huacal verde - Grande",
                            Existencia = 150
                        },
                        new
                        {
                            IdTipo = 3,
                            Descripcion = "Huacal verde - Pequeña",
                            Existencia = 200
                        },
                        new
                        {
                            IdTipo = 4,
                            Descripcion = "Huacal Rojo - Pequeña",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("P1_ap1_FelixMunoz.Models.EntradasHuacalesDetalle", b =>
                {
                    b.HasOne("P1_ap1_FelixMunoz.Models.EntradasHuacales", "EntradaHuacal")
                        .WithMany("DetalleHuacales")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P1_ap1_FelixMunoz.Models.TiposHuacales", "TipoHuacal")
                        .WithMany("EntradasHuacalesDetalle")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacal");

                    b.Navigation("TipoHuacal");
                });

            modelBuilder.Entity("P1_ap1_FelixMunoz.Models.EntradasHuacales", b =>
                {
                    b.Navigation("DetalleHuacales");
                });

            modelBuilder.Entity("P1_ap1_FelixMunoz.Models.TiposHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
